/**
 * GENERATED by ../build-basemap.mjs —— 不要手改。
 *
 * 内置底图的清单：路径、真实 sha256、真实字节数。字节本身在同目录的 payload 模块里，
 * 由 `../index.ts` 动态 import 取，所以清单可以被静态引用而不把几十万字节拖进首包。
 * 这些件是**随包发布的内置数据，不是素材**：不进货架、不进 artifact_revisions、没有份数。
 */

export interface BuiltInGeoAsset {
  path: string;
  sha256: string;
  byteSize: number;
  featureCount: number;
  mediaType: "application/geo+json";
  licenseCode: "PDM" | "CC0";
  attribution: string;
}

export const BUILT_IN_GEO_ASSETS: readonly BuiltInGeoAsset[] = Object.freeze([
  {
    path: "geo/ne-110m-land.geojson",
    sha256: "b35cc595de8fb964f65dc174c248b932aa87ca1310a59a39f2e5f4f98d4e3d5a",
    byteSize: 172944,
    featureCount: 177,
    mediaType: "application/geo+json",
    licenseCode: "PDM",
    attribution: "Natural Earth 5.1.1 admin-0 countries，1:110m，公有领域（PDM）",
  },
  {
    path: "plan/grid-1m.geojson",
    sha256: "56ab35059d56358fddd0edf52edc44e0e6c1e6639879b69a63e6ee00d3b9d132",
    byteSize: 7766,
    featureCount: 44,
    mediaType: "application/geo+json",
    licenseCode: "CC0",
    attribution: "OceanLeo 量图纸 1 m 网格（24 m × 18 m）",
  },
  {
    path: "plan/sheet.geojson",
    sha256: "e51a50dee86a151f76ae4bfa7b530a49967119c73fd6d4035c909fe873e4fee1",
    byteSize: 319,
    featureCount: 1,
    mediaType: "application/geo+json",
    licenseCode: "CC0",
    attribution: "OceanLeo 量图纸边框（24 m × 18 m）",
  },
]);

export const PLAN_METRE_IN_DEGREES = 0.000008983152841195212;
export const PLAN_WIDTH_METRES = 24;
export const PLAN_HEIGHT_METRES = 18;
