import assert from "node:assert/strict";
import test from "node:test";
import JSZip from "jszip";

import { markdownToShareBlocks } from "../src/shell/share/share-blocks.ts";
import {
  shareDocxOutline,
  shareMessagesToDocxBlob,
} from "../src/shell/share/share-docx.ts";

const markdown = [
  "# 同比结论",
  "",
  "## 口径",
  "",
  "同比 **增长** 12%，口径见下表。",
  "",
  "1. 取出两年同月的收入",
  "2. 相除减一",
  "   1. 注意闰月",
  "",
  "- 数据来自上传的 xlsx",
  "",
  "```python",
  "ratio = this_year / last_year - 1",
  "print(ratio)",
  "```",
  "",
  "| 月份 | 今年 | 去年 |",
  "| --- | --- | --- |",
  "| 1 月 | 120 | 100 |",
  "| 2 月 | 130 | 110 |",
  "",
  "$$r = \\frac{a}{b} - 1$$",
  "",
  "> 原始数据没有做去重。",
].join("\n");

const input = {
  title: "同比分析",
  subtitle: "OceanLeo · 2026-08-20",
  brand: "Generated by OceanLeo",
  linkText: "https://oceanleo.com/share/abc123",
  messages: [
    {
      role: "user",
      speaker: "我",
      blocks: markdownToShareBlocks("帮我把这个 xlsx 里的数据算个同比"),
    },
    {
      role: "assistant",
      speaker: "OceanLeo",
      blocks: markdownToShareBlocks(markdown),
    },
  ],
};

let files = null;

async function docxFiles() {
  if (files) return files;
  const blob = await shareMessagesToDocxBlob(input);
  const zip = await JSZip.loadAsync(await blob.arrayBuffer());
  const read = async (name) => {
    const entry = zip.file(name);
    return entry ? entry.async("string") : "";
  };
  files = {
    names: Object.keys(zip.files),
    document: await read("word/document.xml"),
    styles: await read("word/styles.xml"),
    numbering: await read("word/numbering.xml"),
    header: await read("word/header1.xml"),
    footer: await read("word/footer1.xml"),
    size: blob.size,
  };
  return files;
}

test("大纲覆盖标题、代码块、列表、表格、公式", () => {
  const outline = shareDocxOutline(input);
  assert.ok(outline.includes("TITLE 同比分析"));
  assert.ok(outline.includes("H1 同比结论"));
  assert.ok(outline.includes("H2 口径"));
  assert.ok(outline.some((line) => line.startsWith("CODE(python)")));
  assert.ok(outline.includes("LIST(ordered) 3"));
  assert.ok(outline.includes("LIST(bullet) 1"));
  assert.ok(outline.includes("TABLE 3x2"));
  assert.ok(outline.some((line) => line.startsWith("MATH")));
});

test("生成的是能被 Word 打开的 OOXML 包，而不是 markdown 硬转", async () => {
  const zip = await docxFiles();
  assert.ok(zip.size > 4000, "文件不该是空壳");
  for (const name of [
    "[Content_Types].xml",
    "word/document.xml",
    "word/styles.xml",
    "word/numbering.xml",
  ]) {
    assert.ok(zip.names.includes(name), `缺 ${name}`);
  }
});

test("标题层级映射到 Word 内置样式", async () => {
  const zip = await docxFiles();
  assert.match(zip.document, /w:pStyle w:val="Heading1"/);
  assert.match(zip.document, /w:pStyle w:val="Heading2"/);
  assert.match(zip.document, /w:pStyle w:val="Title"/);
});

test("代码块用等宽样式，不是普通段落", async () => {
  const zip = await docxFiles();
  assert.match(zip.styles, /w:styleId="OceanLeoShareCode"/);
  assert.match(zip.document, /w:pStyle w:val="OceanLeoShareCode"/);
  assert.match(zip.styles, /Consolas/);
  assert.ok(zip.document.includes("ratio = this_year / last_year - 1"));
});

test("列表是真正的编号定义，不是手打的 1. 2. 3.", async () => {
  const zip = await docxFiles();
  assert.match(zip.document, /<w:numPr>/);
  assert.match(zip.numbering, /w:numFmt w:val="decimal"/);
  assert.match(zip.numbering, /w:numFmt w:val="bullet"/);
  assert.match(zip.numbering, /w:numFmt w:val="lowerLetter"/);
  // 正文里不该出现被硬拼进去的序号前缀
  assert.doesNotMatch(zip.document, /<w:t[^>]*>1\.<\/w:t>/);
});

test("表格是真表格，首行有底纹与全边框", async () => {
  const zip = await docxFiles();
  assert.match(zip.document, /<w:tbl>/);
  assert.match(zip.document, /<w:tblBorders>/);
  assert.match(zip.document, /w:tblHeader/);
  assert.ok(zip.document.includes("月份"));
  assert.ok(zip.document.includes("130"));
});

test("有页眉页脚，页脚带品牌行与页码域", async () => {
  const zip = await docxFiles();
  assert.ok(zip.names.includes("word/header1.xml"));
  assert.ok(zip.names.includes("word/footer1.xml"));
  assert.ok(zip.footer.includes("Generated by OceanLeo"));
  assert.match(zip.footer, /PAGE/);
  assert.match(zip.footer, /NUMPAGES/);
  assert.ok(zip.header.includes("同比分析"));
});

test("说话人分节保留，公式以 TeX 原文落纸", async () => {
  const zip = await docxFiles();
  assert.match(zip.document, /w:pStyle w:val="OceanLeoShareSpeaker"/);
  assert.ok(zip.document.includes("OceanLeo"));
  assert.ok(zip.document.includes("r = \\frac{a}{b} - 1"));
});
