import assert from "node:assert/strict";
import test from "node:test";

import {
  markdownToShareBlocks,
  inlinesToPlainText,
} from "../src/shell/share/share-blocks.ts";
import {
  SHARE_CARD_WIDTH,
  SHARE_MAX_PAGE_HEIGHT,
  SHARE_MIN_TABLE_FONT,
  layoutShareCard,
  planTableColumns,
} from "../src/shell/share/share-layout.ts";

/** 决定性测量器：宽度只跟字数与字号有关，不需要浏览器。 */
const measure = {
  measureText: (text, font) => String(text).length * font.size * 0.6,
  measureMath: (tex, display) => ({
    width: Math.min(600, tex.length * 9),
    height: display ? 46 : 20,
  }),
  imageSize: () => ({ width: 1200, height: 800 }),
};

const measureWithoutMath = {
  measureText: measure.measureText,
  imageSize: measure.imageSize,
};

const labels = {
  title: "同比分析",
  subtitle: "2026-08-20",
  brand: "Generated by OceanLeo",
  tagline: "在 OceanLeo 上生成图片、文档、网站和小工具。",
  linkText: "https://oceanleo.com/share/abc123",
  tableTruncated: "完整表格见原对话",
  pageIndicator: "{index}/{total}",
};

function textItems(page) {
  return page.items.filter((item) => item.kind === "text");
}

function allTexts(page) {
  return textItems(page).map((item) => item.text);
}

// ---------------------------------------------------------------------------
// markdown → 块 IR
// ---------------------------------------------------------------------------

test("markdown 解析出标题、段落、代码块、列表、表格、公式、分割线", () => {
  const blocks = markdownToShareBlocks(
    [
      "# 结论",
      "",
      "同比 **增长** 了 `12%`，见 [明细](https://example.com)。",
      "",
      "$$E = mc^2$$",
      "",
      "行内公式 $a^2+b^2$ 也要认。",
      "",
      "```python",
      "print('hi')",
      "```",
      "",
      "1. 先算总量",
      "2. 再算同比",
      "   - 去年同期",
      "",
      "| 月份 | 收入 |",
      "| --- | --- |",
      "| 1 月 | 100 |",
      "",
      "---",
      "",
      "> 数据来自用户上传的 xlsx。",
    ].join("\n"),
  );
  const kinds = blocks.map((block) => block.type);
  assert.ok(kinds.includes("heading"));
  assert.ok(kinds.includes("code"));
  assert.ok(kinds.includes("list"));
  assert.ok(kinds.includes("table"));
  assert.ok(kinds.includes("rule"));
  assert.ok(kinds.includes("quote"));

  const displayMath = blocks.find((block) => block.type === "math");
  assert.equal(displayMath.tex, "E = mc^2");

  const inlineMathParagraph = blocks.find(
    (block) =>
      block.type === "paragraph" &&
      block.inlines.some((inline) => inline.type === "math"),
  );
  assert.equal(
    inlineMathParagraph.inlines.find((inline) => inline.type === "math").tex,
    "a^2+b^2",
  );

  const code = blocks.find((block) => block.type === "code");
  assert.equal(code.lang, "python");
  assert.deepEqual(code.lines, ["print('hi')"]);

  const list = blocks.find((block) => block.type === "list");
  assert.equal(list.ordered, true);
  assert.equal(list.items[0].index, 1);
  assert.equal(list.items[2].depth, 1);

  const table = blocks.find((block) => block.type === "table");
  assert.deepEqual(table.header.map(inlinesToPlainText), ["月份", "收入"]);
  assert.deepEqual(table.rows[0].map(inlinesToPlainText), ["1 月", "100"]);

  const paragraph = blocks.find(
    (block) =>
      block.type === "paragraph" &&
      inlinesToPlainText(block.inlines).includes("同比"),
  );
  assert.ok(paragraph.inlines.some((inline) => inline.bold));
  assert.ok(paragraph.inlines.some((inline) => inline.code));
  assert.ok(paragraph.inlines.some((inline) => inline.href));
});

test("围栏代码块里的 $$ 不会被当成公式切开", () => {
  const blocks = markdownToShareBlocks(
    ["```bash", "echo $$ && echo done", "```"].join("\n"),
  );
  assert.equal(blocks.length, 1);
  assert.equal(blocks[0].type, "code");
  assert.equal(blocks[0].lines[0], "echo $$ && echo done");
});

// ---------------------------------------------------------------------------
// 长图版式
// ---------------------------------------------------------------------------

function conversation(markdown) {
  return [
    { role: "user", speaker: "我", blocks: markdownToShareBlocks("帮我算个同比") },
    {
      role: "assistant",
      speaker: "OceanLeo",
      blocks: markdownToShareBlocks(markdown),
    },
  ];
}

test("普通会话排成一张 750px 宽的卡片，含页眉页脚与二维码", () => {
  const qr = [
    [true, false, true],
    [false, true, false],
    [true, false, true],
  ];
  const result = layoutShareCard(
    conversation("# 结论\n\n同比增长 12%。\n\n```py\nprint(1)\n```"),
    labels,
    measure,
    { qrModules: qr },
  );
  assert.equal(result.width, SHARE_CARD_WIDTH);
  assert.equal(result.pages.length, 1);
  const page = result.pages[0];
  assert.equal(page.width, SHARE_CARD_WIDTH);
  assert.ok(page.height <= SHARE_MAX_PAGE_HEIGHT);
  assert.ok(allTexts(page).includes("同比分析"));
  assert.ok(allTexts(page).includes("Generated by OceanLeo"));
  assert.equal(page.items.filter((item) => item.kind === "qr").length, 1);
  // 单页时不出现 1/1 页码
  assert.ok(!allTexts(page).includes("1/1"));
});

test("代码块有等宽字体与深色背景，列表有缩进，表格有边框", () => {
  const result = layoutShareCard(
    conversation(
      [
        "```js",
        "const a = 1;",
        "```",
        "",
        "- 第一条",
        "- 第二条",
        "",
        "| a | b |",
        "| --- | --- |",
        "| 1 | 2 |",
      ].join("\n"),
    ),
    labels,
    measure,
  );
  const page = result.pages[0];
  const monoText = textItems(page).filter((item) => item.font.mono);
  assert.ok(monoText.some((item) => item.text === "const a = 1;"));
  assert.ok(
    page.items.some(
      (item) => item.kind === "rect" && item.fill === "#1c1917",
    ),
    "代码块要有深色背景",
  );
  const markers = allTexts(page).filter((text) => text === "•");
  assert.equal(markers.length, 2);
  const bulletX = textItems(page).find((item) => item.text === "第一条").x;
  const markerX = textItems(page).find((item) => item.text === "•").x;
  assert.ok(bulletX > markerX, "列表文字要缩进到项目符号右边");
  assert.ok(
    page.items.some(
      (item) => item.kind === "rect" && item.stroke === "#e7e5e4",
    ),
    "表格要有边框",
  );
});

test("公式走注入的渲染器；渲染器缺席时退回等宽文本且被计数", () => {
  const withMath = layoutShareCard(
    conversation("$$\\int_0^1 x dx$$ 与 $x^2$ 同时出现。"),
    labels,
    measure,
  );
  const mathItems = withMath.pages[0].items.filter(
    (item) => item.kind === "math",
  );
  assert.equal(withMath.fallbackFormulas, 0);
  assert.ok(mathItems.some((item) => item.display === true));
  assert.ok(mathItems.some((item) => item.display === false));

  const withoutMath = layoutShareCard(
    conversation("$$\\int_0^1 x dx$$ 与 $x^2$ 同时出现。"),
    labels,
    measureWithoutMath,
  );
  assert.equal(
    withoutMath.pages[0].items.filter((item) => item.kind === "math").length,
    0,
  );
  assert.ok(withoutMath.fallbackFormulas >= 2);
});

// ---------------------------------------------------------------------------
// R6 三条规则
// ---------------------------------------------------------------------------

test("R6 宽表：先整体等比缩放", () => {
  // 9 列 × 87px ≈ 785px，比 646px 的正文宽略宽一点：应当整体缩放而不是裁列。
  const columns = Array.from({ length: 9 }, () => [
    "标题标题标题",
    "内容内容内容内容",
  ]);
  const plan = planTableColumns(columns, 646, measure, 14);
  assert.equal(plan.keptColumns, plan.totalColumns);
  assert.ok(plan.font.size < 14, "放不下时字号要缩小");
  assert.ok(plan.font.size >= SHARE_MIN_TABLE_FONT);
  const total = plan.widths.reduce((sum, width) => sum + width, 0);
  assert.ok(total <= 646 + 1);
});

test("R6 宽表：缩到最小可读字号仍放不下 → 保留前若干列并标注", () => {
  const wide = [
    ["月份", "1 月"],
    ...Array.from({ length: 24 }, (_, index) => [
      `很长的表头名称 ${index}`,
      `很长的数据单元格内容 ${index}`,
    ]),
  ];
  const plan = planTableColumns(wide, 646, measure, 14);
  assert.equal(plan.font.size, SHARE_MIN_TABLE_FONT);
  assert.ok(plan.keptColumns < plan.totalColumns);
  assert.ok(plan.keptColumns >= 1);

  const header = wide.map((column) => column[0]);
  const row = wide.map((column) => column[1]);
  const markdown = [
    `| ${header.join(" | ")} |`,
    `| ${header.map(() => "---").join(" | ")} |`,
    `| ${row.join(" | ")} |`,
  ].join("\n");
  const result = layoutShareCard(conversation(markdown), labels, measure);
  assert.equal(result.truncatedTables, 1);
  assert.ok(
    result.pages.some((page) => allTexts(page).includes("完整表格见原对话")),
  );
});

test("R6 超长：单页不超过 12000px，超出自动分片并标 i/N", () => {
  const long = Array.from(
    { length: 400 },
    (_, index) => `第 ${index} 段：这是一段足够长的正文，用来把长图撑过一页的高度上限。`,
  ).join("\n\n");
  const result = layoutShareCard(conversation(long), labels, measure);
  assert.ok(result.pages.length >= 2, "应当切成多张");
  for (const page of result.pages) {
    assert.ok(
      page.height <= SHARE_MAX_PAGE_HEIGHT,
      `第 ${page.index} 张高 ${page.height}，超过了 12000`,
    );
  }
  const total = result.pages.length;
  for (const page of result.pages) {
    assert.ok(
      allTexts(page).includes(`${page.index}/${total}`),
      `第 ${page.index} 张缺页码`,
    );
  }
  assert.deepEqual(
    result.pages.map((page) => page.index),
    Array.from({ length: total }, (_, index) => index + 1),
  );
});

test("上限可调，按更小的上限会切出更多张", () => {
  const long = Array.from(
    { length: 60 },
    (_, index) => `第 ${index} 段正文。`,
  ).join("\n\n");
  const small = layoutShareCard(conversation(long), labels, measure, {
    maxPageHeight: 900,
  });
  assert.ok(small.pages.length > 1);
  for (const page of small.pages) assert.ok(page.height <= 900);
});
