import type { UITranslate } from "../../i18n/ui/useUI";
import type { SelectionContext } from "../selection-context";
import type { DeckEditorState } from "./use-deck-editor";

export function deckSlideSelectionContext(
  editor: DeckEditorState,
  tt: UITranslate,
): SelectionContext {
  const slide = editor.activeSlide;
  return {
    version: 1,
    kind: "slide",
    id: `slide:${slide.id}`,
    label: tt("第 {page} 页", { page: editor.activeIndex + 1 }),
    controls: [
      {
        id: "layout",
        kind: "select",
        label: tt("版式"),
        icon: "templates",
        value: slide.layout,
        options: [
          { value: "title", label: tt("封面") },
          { value: "title-body", label: tt("标题与正文") },
          { value: "section", label: tt("章节") },
          { value: "bullets", label: tt("项目符号") },
          { value: "image-left", label: tt("左图右文") },
          { value: "image-right", label: tt("左文右图") },
          { value: "blank", label: tt("空白") },
        ],
      },
      {
        id: "background",
        kind: "color",
        label: tt("页面背景"),
        icon: "background",
        value: slide.background || "#ffffff",
      },
      {
        id: "transition",
        kind: "select",
        label: tt("过渡"),
        icon: "animate",
        value: slide.transition?.type || "none",
        options: [
          { value: "none", label: tt("无") },
          { value: "fade", label: tt("淡入") },
          { value: "push-left", label: tt("向左推进") },
          { value: "push-right", label: tt("向右推进") },
          { value: "wipe", label: tt("擦除") },
          { value: "zoom", label: tt("缩放") },
        ],
      },
      ...(slide.transition
        ? [
            {
              id: "transition-duration",
              kind: "range" as const,
              label: tt("过渡时长"),
              value: slide.transition.durationMs,
              min: 100,
              max: 3_000,
              step: 50,
              slot: "inspector" as const,
              inspectorGroup: "deck-slide-transition",
              inspectorLabel: tt("页面过渡"),
              inspectorIcon: "animate" as const,
            },
          ]
        : []),
      {
        id: "master",
        kind: "select",
        label: tt("母版"),
        value: editor.activeMaster.id,
        options: editor.deck.masters.map((master) => ({
          value: master.id,
          label: master.name,
        })),
        slot: "inspector",
        inspectorGroup: "deck-master",
        inspectorLabel: tt("母版与版式"),
        inspectorIcon: "templates",
      },
      {
        id: "master-name",
        kind: "text",
        label: tt("母版名称"),
        value: editor.activeMaster.name,
        slot: "inspector",
        inspectorGroup: "deck-master",
        inspectorLabel: tt("母版与版式"),
        inspectorIcon: "templates",
      },
      {
        id: "master-background",
        kind: "color",
        label: tt("母版背景"),
        value: editor.activeMaster.background,
        slot: "inspector",
        inspectorGroup: "deck-master",
        inspectorLabel: tt("母版与版式"),
        inspectorIcon: "background",
      },
      {
        id: "master-text-color",
        kind: "color",
        label: tt("母版文字色"),
        value: editor.activeMaster.textColor,
        slot: "inspector",
        inspectorGroup: "deck-master",
        inspectorLabel: tt("母版与版式"),
        inspectorIcon: "text",
      },
      {
        id: "master-accent-color",
        kind: "color",
        label: tt("母版强调色"),
        value: editor.activeMaster.accentColor,
        slot: "inspector",
        inspectorGroup: "deck-master",
        inspectorLabel: tt("母版与版式"),
        inspectorIcon: "background",
      },
      {
        id: "master-font-family",
        kind: "text",
        label: tt("母版字体"),
        value: editor.activeMaster.fontFamily,
        slot: "inspector",
        inspectorGroup: "deck-master",
        inspectorLabel: tt("母版与版式"),
        inspectorIcon: "font",
      },
      {
        id: "master-duplicate",
        kind: "action",
        label: tt("复制为新母版"),
        slot: "inspector",
        inspectorGroup: "deck-master",
        inspectorLabel: tt("母版与版式"),
        inspectorIcon: "templates",
      },
      {
        id: "master-delete",
        kind: "action",
        label: tt("删除当前母版"),
        danger: true,
        disabled: editor.deck.masters.length <= 1,
        slot: "inspector",
        inspectorGroup: "deck-master",
        inspectorLabel: tt("母版与版式"),
        inspectorIcon: "templates",
      },
      {
        id: "title",
        kind: "text",
        label: tt("页面标题"),
        value: slide.title,
        slot: "inspector",
        inspectorGroup: "deck-slide-content",
        inspectorLabel: tt("页面内容"),
        inspectorIcon: "text",
      },
      {
        id: "body",
        kind: "text",
        label: tt("页面正文"),
        value: slide.body,
        slot: "inspector",
        inspectorGroup: "deck-slide-content",
        inspectorLabel: tt("页面内容"),
        inspectorIcon: "text",
      },
      {
        id: "notes",
        kind: "text",
        label: tt("演讲者备注"),
        value: slide.notes,
        slot: "inspector",
        inspectorGroup: "deck-slide-notes",
        inspectorLabel: tt("演讲者备注"),
        inspectorIcon: "note",
      },
      {
        id: "duplicate-slide",
        kind: "action",
        label: tt("复制页面"),
        icon: "duplicate",
      },
      {
        id: "delete-slide",
        kind: "action",
        label: tt("删除页面"),
        icon: "delete",
        danger: true,
        disabled: editor.deck.slides.length <= 1,
      },
    ],
  };
}
