"use client";

// ============================================================================
// @oceanleo/ui — 分享卡片（Generate Image 的构图 + 预览）
// ----------------------------------------------------------------------------
// 「卡片」不是聊天页的截图，是一份**专门设计的版面**：固定 750 CSS px 宽、白色圆角
// 卡、用户气泡靠右、助手正文靠左、页脚是「Generated by OceanLeo」+ 二维码 + 一句
// 功能说明。构图在这里，排版在 `share-layout.ts`，落笔在 `share-image.ts`。
// ============================================================================

import { useEffect, useState } from "react";
import type { AgentMessage } from "../../lib/agent";
import { useUI, type UITranslate } from "../../i18n/ui/useUI";
import { markdownToShareBlocks, type ShareBlock } from "./share-blocks";
import type { ShareCardLabels, ShareCardMessage } from "./share-layout";
import {
  downloadBlobs,
  renderShareCardImages,
  type ShareCardImages,
} from "./share-image";
import type { ShareSelectableMessage } from "./share-selection";

export interface ShareSpeakerLabels {
  user: string;
  assistant: string;
}

/** 一条对话消息 → 卡片上的块。产物与附件也要露脸，否则导出的图会缺一块。 */
export function shareBlocksForMessage(
  message: ShareSelectableMessage,
  tt: UITranslate,
): ShareBlock[] {
  const blocks: ShareBlock[] = [];
  const attachments = message.meta?.attachments || [];
  for (const attachment of attachments) {
    const url = String(attachment.url || "");
    const isImage =
      String(attachment.mime || "").startsWith("image/") ||
      attachment.media_type === "image" ||
      /\.(png|jpe?g|webp|gif)$/i.test(url.split("?")[0]);
    if (isImage && url) {
      blocks.push({ type: "image", src: url, alt: attachment.name || "" });
    } else if (url || attachment.name) {
      blocks.push({
        type: "quote",
        inlines: [
          {
            type: "text",
            text: `${tt("附件")} · ${attachment.name || url}`,
          },
        ],
      });
    }
  }
  blocks.push(...markdownToShareBlocks(message.content || ""));
  const artifact = message.meta?.artifact;
  const imageUrl =
    (typeof message.meta?.image_url === "string" ? message.meta.image_url : "") ||
    (artifact && /^image$/i.test(artifact.type || "") ? artifact.url || "" : "");
  if (imageUrl) {
    blocks.push({ type: "image", src: imageUrl, alt: artifact?.title || "" });
  } else if (artifact) {
    blocks.push({
      type: "quote",
      inlines: [
        {
          type: "text",
          text: tt("已生成「{label}」", {
            label: artifact.title || artifact.type || tt("结果"),
          }),
        },
      ],
    });
  }
  return blocks;
}

export function buildShareCardMessages(
  messages: readonly ShareSelectableMessage[],
  speakers: ShareSpeakerLabels,
  tt: UITranslate,
): ShareCardMessage[] {
  return messages
    .map((message) => ({
      role: message.role,
      speaker: message.role === "user" ? speakers.user : speakers.assistant,
      blocks: shareBlocksForMessage(message, tt),
    }))
    .filter((message) => message.blocks.length > 0);
}

export function shareCardLabels(
  tt: UITranslate,
  options: { title?: string; siteLabel?: string; link?: string },
): ShareCardLabels {
  const date = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  });
  return {
    title: (options.title || "").trim() || tt("与 OceanLeo 的对话"),
    subtitle: [options.siteLabel, date].filter(Boolean).join(" · "),
    brand: "Generated by OceanLeo",
    tagline: tt("在 OceanLeo 上直接出图、写文档、做网站和小工具。"),
    linkText: options.link,
    tableTruncated: tt("完整表格见原对话"),
    pageIndicator: "{index}/{total}",
  };
}

export interface GenerateShareCardInput {
  messages: readonly AgentMessage[];
  speakers: ShareSpeakerLabels;
  title?: string;
  siteLabel?: string;
  /** 二维码与页脚要回链的地址（Copy Link 拿到的那个）。 */
  link?: string;
  tt: UITranslate;
}

export async function generateShareCard(
  input: GenerateShareCardInput,
): Promise<ShareCardImages> {
  const cardMessages = buildShareCardMessages(
    input.messages,
    input.speakers,
    input.tt,
  );
  if (!cardMessages.length) {
    throw new Error("没有可以生成长图的内容。");
  }
  return renderShareCardImages({
    messages: cardMessages,
    labels: shareCardLabels(input.tt, {
      title: input.title,
      siteLabel: input.siteLabel,
      link: input.link,
    }),
    qrText: input.link,
  });
}

// ---------------------------------------------------------------------------
// 预览
// ---------------------------------------------------------------------------

export function ShareCardPreview({
  images,
  fileBaseName,
  onClose,
}: {
  images: ShareCardImages;
  fileBaseName: string;
  onClose: () => void;
}) {
  const tt = useUI();
  const [urls, setUrls] = useState<string[]>([]);

  useEffect(() => {
    const created = images.blobs.map((blob) => URL.createObjectURL(blob));
    setUrls(created);
    return () => {
      for (const url of created) URL.revokeObjectURL(url);
    };
  }, [images]);

  const total = images.blobs.length;
  return (
    <div
      className="fixed inset-0 z-[80] flex flex-col bg-stone-900/70 backdrop-blur-sm"
      role="dialog"
      aria-modal="true"
      aria-label={tt("长图预览")}
    >
      <div className="flex shrink-0 items-center justify-between gap-3 px-4 py-3 text-white">
        <span className="text-[14px] font-medium">
          {total > 1
            ? tt("长图已生成 · 共 {count} 张", { count: total })
            : tt("长图已生成")}
        </span>
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => downloadBlobs(images.blobs, fileBaseName)}
            className="rounded-lg bg-white px-3 py-1.5 text-[13px] font-semibold text-stone-900 transition duration-[var(--leo-dur-2)] ease-[var(--leo-ease-standard)] active:duration-[var(--leo-dur-1)] hover:bg-stone-100 active:scale-95"
          >
            {tt("下载")}
          </button>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg border border-white/40 px-3 py-1.5 text-[13px] font-medium text-white transition duration-[var(--leo-dur-2)] ease-[var(--leo-ease-standard)] active:duration-[var(--leo-dur-1)] hover:bg-white/10 active:scale-95"
          >
            {tt("关闭")}
          </button>
        </div>
      </div>
      <div className="min-h-0 flex-1 overflow-y-auto px-4 pb-6">
        <div className="mx-auto flex w-full max-w-[420px] flex-col items-center gap-4">
          {urls.map((url, index) => (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              key={url}
              src={url}
              alt={tt("长图第 {index} 张", { index: index + 1 })}
              className="w-full rounded-xl shadow-2xl"
            />
          ))}
        </div>
      </div>
    </div>
  );
}
