// ============================================================================
// @oceanleo/ui — 分享长图的排版引擎（纯函数，无 DOM）
// ----------------------------------------------------------------------------
// 这里只算「什么东西画在哪」，产出一张扁平的绘制清单；真正落笔的是
// `share-image.ts`。分成两层是为了两件事：
//   1. 合同 R6 的三条规则（公式 / 宽表 / 超长切片）能在 node 里直接断言，
//      不需要浏览器、不需要截图；
//   2. 画笔变成傻子，只认清单，不再懂业务。
//
// 版式是**我们自己设计的卡片**，不是网页截图：固定 750 CSS px 宽、白色圆角卡、
// 用户气泡靠右、助手正文靠左、页脚有品牌行 + 二维码 + 一句功能说明。
// ============================================================================

import type { ShareBlock, ShareInline, ShareListItem } from "./share-blocks";
import { inlinesToPlainText } from "./share-blocks";

// ---------------------------------------------------------------------------
// 尺寸与配色（一处改，长图整体跟着变）
// ---------------------------------------------------------------------------

export const SHARE_CARD_WIDTH = 750;
/** 合同 R6：单张画布高度上限，保守覆盖 iOS Safari 的画布面积限制。 */
export const SHARE_MAX_PAGE_HEIGHT = 12000;
/** 宽表缩到这个字号仍放不下，就改成「保留前若干列 + 标注」。 */
export const SHARE_MIN_TABLE_FONT = 11;

const PAGE_MARGIN = 24;
const CARD_PADDING = 28;
const BUBBLE_PADDING_X = 18;
const BUBBLE_PADDING_Y = 14;
const USER_BUBBLE_MAX_RATIO = 0.78;
const BLOCK_GAP = 10;
const SECTION_GAP = 22;
const TABLE_CELL_PADDING = 10;
const CODE_PADDING = 14;
const QR_SIZE = 88;

export const SHARE_COLORS = {
  pageBackground: "#efeeec",
  card: "#ffffff",
  cardBorder: "#e7e5e4",
  text: "#1c1917",
  muted: "#78716c",
  faint: "#a8a29e",
  userBubble: "#f5f5f4",
  quoteBar: "#d6d3d1",
  codeBackground: "#1c1917",
  codeText: "#e7e5e4",
  codeGutter: "#292524",
  tableHeader: "#f5f5f4",
  tableBorder: "#e7e5e4",
  rule: "#e7e5e4",
  accent: "#4f46e5",
} as const;

export interface ShareFont {
  size: number;
  weight: number;
  mono: boolean;
  italic?: boolean;
}

export const SHARE_SANS_STACK =
  '"Noto Sans SC", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif';
export const SHARE_MONO_STACK =
  '"JetBrains Mono", "SFMono-Regular", Menlo, Consolas, "Noto Sans Mono CJK SC", monospace';

/** 画笔与测量器必须用同一个字体串，否则量出来的宽度对不上画出来的字。 */
export function shareFontCss(font: ShareFont): string {
  const style = font.italic ? "italic " : "";
  const family = font.mono ? SHARE_MONO_STACK : SHARE_SANS_STACK;
  return `${style}${font.weight} ${font.size}px ${family}`;
}

function sans(size: number, weight = 400, italic = false): ShareFont {
  return { size, weight, mono: false, italic };
}

function mono(size: number, weight = 400): ShareFont {
  return { size, weight, mono: true };
}

// ---------------------------------------------------------------------------
// 绘制清单
// ---------------------------------------------------------------------------

export type ShareDrawItem =
  | {
      kind: "rect";
      x: number;
      y: number;
      width: number;
      height: number;
      fill?: string;
      stroke?: string;
      radius?: number;
      lineWidth?: number;
    }
  | {
      kind: "text";
      x: number;
      y: number;
      text: string;
      font: ShareFont;
      color: string;
      align?: "left" | "center" | "right";
      underline?: boolean;
      strike?: boolean;
    }
  | {
      kind: "line";
      x: number;
      y: number;
      width: number;
      color: string;
      thickness: number;
    }
  | {
      kind: "image";
      x: number;
      y: number;
      width: number;
      height: number;
      src: string;
      radius?: number;
    }
  | {
      kind: "math";
      x: number;
      y: number;
      width: number;
      height: number;
      tex: string;
      display: boolean;
    }
  | {
      kind: "qr";
      x: number;
      y: number;
      size: number;
      modules: readonly (readonly boolean[])[];
    };

export interface SharePage {
  /** 1 起。 */
  index: number;
  width: number;
  height: number;
  items: ShareDrawItem[];
}

export interface ShareLayoutResult {
  width: number;
  pages: SharePage[];
  /** 被「保留前若干列」处理过的表格数量（>0 时图上已有标注）。 */
  truncatedTables: number;
  /** 用兜底等宽文本画的公式数量（测量器没给尺寸时）。 */
  fallbackFormulas: number;
}

// ---------------------------------------------------------------------------
// 输入
// ---------------------------------------------------------------------------

export interface ShareCardMessage {
  role: "user" | "assistant";
  /** 说话人标签（已过 i18n）。 */
  speaker: string;
  blocks: ShareBlock[];
}

export interface ShareCardLabels {
  /** 卡片标题（一般是本次对话的总结）。 */
  title: string;
  /** 标题下的一行小字，如日期或站点名。 */
  subtitle?: string;
  /** 页脚品牌行，如「Generated by OceanLeo」。 */
  brand: string;
  /** 页脚那一行功能说明。 */
  tagline: string;
  /** 二维码旁的短链文案（一般就是分享链接本身）。 */
  linkText?: string;
  /** 宽表被裁列时画在表下的那句话。 */
  tableTruncated: string;
  /** 分片页码，形如 `{index}/{total}`。 */
  pageIndicator: string;
}

export interface ShareMeasureContext {
  measureText(text: string, font: ShareFont): number;
  /** 公式测量；返回 null 表示这台机器上没有公式渲染器，走等宽兜底。 */
  measureMath?(
    tex: string,
    display: boolean,
    maxWidth: number,
  ): { width: number; height: number } | null;
  /** 图片自然尺寸；返回 null 就不画这张图。 */
  imageSize?(src: string): { width: number; height: number } | null;
}

export interface ShareLayoutOptions {
  width?: number;
  maxPageHeight?: number;
  qrModules?: readonly (readonly boolean[])[] | null;
}

// ---------------------------------------------------------------------------
// 行内排版
// ---------------------------------------------------------------------------

interface InlineAtom {
  text: string;
  width: number;
  font: ShareFont;
  color: string;
  href?: string;
  strike?: boolean;
  code?: boolean;
  math?: { tex: string; height: number };
  breakBefore?: boolean;
  hardBreak?: boolean;
}

interface LaidLine {
  height: number;
  items: ShareDrawItem[];
}

const CJK = /[\u2e80-\u9fff\u3000-\u303f\uff00-\uffef]/;

/** 断行单元：CJK 逐字，拉丁按词（连着后面的空格一起走）。 */
function textAtoms(text: string): string[] {
  const out: string[] = [];
  let word = "";
  for (const character of text) {
    if (character === "\n") {
      if (word) out.push(word);
      word = "";
      out.push("\n");
      continue;
    }
    if (CJK.test(character)) {
      if (word) out.push(word);
      word = "";
      out.push(character);
      continue;
    }
    word += character;
    if (character === " " || character === "\t") {
      out.push(word);
      word = "";
    }
  }
  if (word) out.push(word);
  return out;
}

interface InlineLayoutOptions {
  baseFont: ShareFont;
  color: string;
  maxWidth: number;
  measure: ShareMeasureContext;
  lineHeightRatio?: number;
  align?: "left" | "right";
  /** 统计兜底公式的次数。 */
  onFallbackFormula?: () => void;
}

function atomsFromInlines(
  inlines: readonly ShareInline[],
  options: InlineLayoutOptions,
): InlineAtom[] {
  const out: InlineAtom[] = [];
  for (const inline of inlines) {
    if (inline.type === "math") {
      const measured = options.measure.measureMath?.(
        inline.tex,
        false,
        options.maxWidth,
      );
      if (measured) {
        out.push({
          text: inline.tex,
          width: measured.width,
          font: options.baseFont,
          color: options.color,
          math: { tex: inline.tex, height: measured.height },
        });
        continue;
      }
      options.onFallbackFormula?.();
      const font = mono(options.baseFont.size - 1);
      out.push({
        text: inline.tex,
        width: options.measure.measureText(inline.tex, font),
        font,
        color: options.color,
        code: true,
      });
      continue;
    }
    const font: ShareFont = {
      size: inline.code ? options.baseFont.size - 1 : options.baseFont.size,
      weight: inline.bold ? 600 : options.baseFont.weight,
      mono: Boolean(inline.code),
      italic: Boolean(inline.italic),
    };
    const color = inline.href
      ? SHARE_COLORS.accent
      : inline.code
        ? SHARE_COLORS.text
        : options.color;
    for (const piece of textAtoms(inline.text)) {
      if (piece === "\n") {
        out.push({
          text: "",
          width: 0,
          font,
          color,
          hardBreak: true,
        });
        continue;
      }
      out.push({
        text: piece,
        width: options.measure.measureText(piece, font),
        font,
        color,
        href: inline.href,
        strike: inline.strike,
        code: inline.code,
      });
    }
  }
  return out;
}

/** 把一串行内片段排成若干行；每行是一个不可再分的排版原子。 */
function layoutInlines(
  inlines: readonly ShareInline[],
  options: InlineLayoutOptions,
): LaidLine[] {
  const atoms = atomsFromInlines(inlines, options);
  const ratio = options.lineHeightRatio ?? 1.62;
  const lines: LaidLine[] = [];
  let row: InlineAtom[] = [];
  let used = 0;

  const flush = () => {
    if (!row.length) {
      lines.push({ height: Math.round(options.baseFont.size * ratio), items: [] });
      return;
    }
    // 行尾空白不参与对齐宽度。
    while (row.length && !row[row.length - 1].text.trim()) row.pop();
    const width = row.reduce((sum, atom) => sum + atom.width, 0);
    const textHeight = Math.round(
      Math.max(...row.map((atom) => atom.font.size)) * ratio,
    );
    const mathHeight = Math.max(
      0,
      ...row.map((atom) => (atom.math ? atom.math.height + 6 : 0)),
    );
    const height = Math.max(textHeight, mathHeight);
    const startX = options.align === "right" ? options.maxWidth - width : 0;
    let cursor = startX;
    const items: ShareDrawItem[] = [];
    let run: { text: string; x: number; atom: InlineAtom } | null = null;
    const closeRun = () => {
      if (!run) return;
      items.push({
        kind: "text",
        x: run.x,
        y: Math.round((height - run.atom.font.size * 1.2) / 2),
        text: run.text,
        font: run.atom.font,
        color: run.atom.color,
        underline: Boolean(run.atom.href),
        strike: Boolean(run.atom.strike),
      });
      run = null;
    };
    for (const atom of row) {
      if (atom.hardBreak) continue;
      if (atom.math) {
        closeRun();
        items.push({
          kind: "math",
          x: cursor,
          y: Math.round((height - atom.math.height) / 2),
          width: atom.width,
          height: atom.math.height,
          tex: atom.math.tex,
          display: false,
        });
        cursor += atom.width;
        continue;
      }
      const sameRun =
        run &&
        run.atom.font.size === atom.font.size &&
        run.atom.font.weight === atom.font.weight &&
        run.atom.font.mono === atom.font.mono &&
        run.atom.font.italic === atom.font.italic &&
        run.atom.color === atom.color &&
        Boolean(run.atom.href) === Boolean(atom.href) &&
        Boolean(run.atom.strike) === Boolean(atom.strike);
      if (sameRun && run) run.text += atom.text;
      else {
        closeRun();
        run = { text: atom.text, x: cursor, atom };
      }
      cursor += atom.width;
    }
    closeRun();
    lines.push({ height, items });
    row = [];
    used = 0;
  };

  for (const atom of atoms) {
    if (atom.hardBreak) {
      flush();
      continue;
    }
    if (used > 0 && used + atom.width > options.maxWidth) flush();
    row.push(atom);
    used += atom.width;
  }
  if (row.length) flush();
  if (!lines.length) {
    lines.push({ height: Math.round(options.baseFont.size * ratio), items: [] });
  }
  return lines;
}

// ---------------------------------------------------------------------------
// 流式行（分页的最小单位）
// ---------------------------------------------------------------------------

interface FlowRow {
  height: number;
  /** 相对本行左上角作画；分页后统一平移。 */
  render: (x: number, y: number) => ShareDrawItem[];
}

interface FlowSection {
  /** 用户气泡要底色；助手正文不要。 */
  bubble: boolean;
  x: number;
  width: number;
  rows: FlowRow[];
}

function shift(items: ShareDrawItem[], dx: number, dy: number): ShareDrawItem[] {
  return items.map((item) => {
    if (item.kind === "line") return { ...item, x: item.x + dx, y: item.y + dy };
    return { ...item, x: item.x + dx, y: item.y + dy } as ShareDrawItem;
  });
}

function spacer(height: number): FlowRow {
  return { height, render: () => [] };
}

function linesToRows(lines: LaidLine[], offsetX = 0): FlowRow[] {
  return lines.map((line) => ({
    height: line.height,
    render: (x: number, y: number) => shift(line.items, x + offsetX, y),
  }));
}

// ---------------------------------------------------------------------------
// 块 → 流式行
// ---------------------------------------------------------------------------

interface BlockContext {
  width: number;
  measure: ShareMeasureContext;
  labels: ShareCardLabels;
  onTruncatedTable: () => void;
  onFallbackFormula: () => void;
}

const HEADING_SIZE = [26, 22, 19, 17, 16, 15];

function headingRows(
  block: Extract<ShareBlock, { type: "heading" }>,
  context: BlockContext,
): FlowRow[] {
  const size = HEADING_SIZE[Math.min(5, block.level - 1)];
  const lines = layoutInlines(block.inlines, {
    baseFont: sans(size, 700),
    color: SHARE_COLORS.text,
    maxWidth: context.width,
    measure: context.measure,
    lineHeightRatio: 1.45,
    onFallbackFormula: context.onFallbackFormula,
  });
  return [spacer(block.level <= 2 ? 12 : 8), ...linesToRows(lines), spacer(4)];
}

function paragraphRows(
  inlines: readonly ShareInline[],
  context: BlockContext,
  font = sans(16),
): FlowRow[] {
  const lines = layoutInlines(inlines, {
    baseFont: font,
    color: SHARE_COLORS.text,
    maxWidth: context.width,
    measure: context.measure,
    onFallbackFormula: context.onFallbackFormula,
  });
  return linesToRows(lines);
}

function quoteRows(
  block: Extract<ShareBlock, { type: "quote" }>,
  context: BlockContext,
): FlowRow[] {
  const inset = 16;
  const lines = layoutInlines(block.inlines, {
    baseFont: sans(15, 400, true),
    color: SHARE_COLORS.muted,
    maxWidth: context.width - inset,
    measure: context.measure,
    onFallbackFormula: context.onFallbackFormula,
  });
  return lines.map((line) => ({
    height: line.height,
    render: (x: number, y: number) => [
      {
        kind: "rect" as const,
        x,
        y,
        width: 3,
        height: line.height,
        fill: SHARE_COLORS.quoteBar,
      },
      ...shift(line.items, x + inset, y),
    ],
  }));
}

function listRows(
  block: Extract<ShareBlock, { type: "list" }>,
  context: BlockContext,
): FlowRow[] {
  const rows: FlowRow[] = [];
  const font = sans(16);
  const markerFont = sans(15, 600);
  for (const item of block.items) {
    const indent = 22 * item.depth;
    const marker = listMarker(item);
    const markerWidth = Math.max(
      22,
      context.measure.measureText(marker, markerFont) + 8,
    );
    const textLeft = indent + markerWidth;
    const lines = layoutInlines(item.inlines, {
      baseFont: font,
      color: SHARE_COLORS.text,
      maxWidth: Math.max(80, context.width - textLeft),
      measure: context.measure,
      onFallbackFormula: context.onFallbackFormula,
    });
    lines.forEach((line, position) => {
      rows.push({
        height: line.height,
        render: (x: number, y: number) => [
          ...(position === 0
            ? [
                {
                  kind: "text" as const,
                  x: x + indent,
                  y: y + Math.round((line.height - markerFont.size * 1.2) / 2),
                  text: marker,
                  font: markerFont,
                  color: SHARE_COLORS.muted,
                },
              ]
            : []),
          ...shift(line.items, x + textLeft, y),
        ],
      });
    });
    rows.push(spacer(4));
  }
  return rows;
}

function listMarker(item: ShareListItem): string {
  if (typeof item.checked === "boolean") return item.checked ? "☑" : "☐";
  if (item.ordered) return `${item.index}.`;
  return item.depth % 2 === 0 ? "•" : "◦";
}

function codeRows(
  block: Extract<ShareBlock, { type: "code" }>,
  context: BlockContext,
): FlowRow[] {
  const font = mono(13.5);
  const lineHeight = 22;
  const innerWidth = context.width - CODE_PADDING * 2;
  const wrapped: string[] = [];
  for (const raw of block.lines) {
    const text = raw.replace(/\t/g, "    ");
    if (context.measure.measureText(text, font) <= innerWidth) {
      wrapped.push(text);
      continue;
    }
    let current = "";
    for (const character of text) {
      const candidate = current + character;
      if (
        current &&
        context.measure.measureText(candidate, font) > innerWidth
      ) {
        wrapped.push(current);
        current = character;
      } else {
        current = candidate;
      }
    }
    wrapped.push(current);
  }
  const rows: FlowRow[] = [];
  const label = block.lang.trim();
  const headerHeight = label ? 26 : 0;
  const width = context.width;
  rows.push(spacer(6));
  if (label) {
    rows.push({
      height: headerHeight,
      render: (x, y) => [
        {
          kind: "rect",
          x,
          y,
          width,
          height: headerHeight,
          fill: SHARE_COLORS.codeGutter,
          radius: 0,
        },
        {
          kind: "text",
          x: x + CODE_PADDING,
          y: y + 6,
          text: label,
          font: mono(11.5, 600),
          color: SHARE_COLORS.faint,
        },
      ],
    });
  }
  rows.push({
    height: CODE_PADDING,
    render: (x, y) => [
      {
        kind: "rect",
        x,
        y,
        width,
        height: CODE_PADDING,
        fill: SHARE_COLORS.codeBackground,
      },
    ],
  });
  wrapped.forEach((line) => {
    rows.push({
      height: lineHeight,
      render: (x, y) => [
        {
          kind: "rect",
          x,
          y,
          width,
          height: lineHeight,
          fill: SHARE_COLORS.codeBackground,
        },
        {
          kind: "text",
          x: x + CODE_PADDING,
          y: y + Math.round((lineHeight - font.size * 1.2) / 2),
          text: line,
          font,
          color: SHARE_COLORS.codeText,
        },
      ],
    });
  });
  rows.push({
    height: CODE_PADDING,
    render: (x, y) => [
      {
        kind: "rect",
        x,
        y,
        width,
        height: CODE_PADDING,
        fill: SHARE_COLORS.codeBackground,
      },
    ],
  });
  rows.push(spacer(8));
  return rows;
}

interface TablePlan {
  widths: number[];
  font: ShareFont;
  keptColumns: number;
  totalColumns: number;
}

/**
 * 合同 R6 的宽表规则：
 *   1. 先整体等比缩放；
 *   2. 缩到最小可读字号（`SHARE_MIN_TABLE_FONT`）仍放不下 → 保留前若干列，
 *      并在图上标注「完整表格见原对话」。
 */
export function planTableColumns(
  columns: string[][],
  contentWidth: number,
  measure: ShareMeasureContext,
  baseSize = 14,
): TablePlan {
  const baseFont = sans(baseSize);
  const natural = columns.map((cell) => {
    const widest = cell.reduce(
      (max, text) => Math.max(max, measure.measureText(text, baseFont)),
      0,
    );
    return Math.min(contentWidth, widest + TABLE_CELL_PADDING * 2);
  });
  const total = natural.reduce((sum, width) => sum + width, 0) || 1;
  if (total <= contentWidth) {
    const extra = (contentWidth - total) / natural.length;
    return {
      widths: natural.map((width) => width + extra),
      font: baseFont,
      keptColumns: natural.length,
      totalColumns: natural.length,
    };
  }
  const scale = contentWidth / total;
  const scaledSize = Math.round(baseSize * scale * 10) / 10;
  if (scaledSize >= SHARE_MIN_TABLE_FONT) {
    return {
      widths: natural.map((width) => width * scale),
      font: sans(scaledSize),
      keptColumns: natural.length,
      totalColumns: natural.length,
    };
  }
  const minScale = SHARE_MIN_TABLE_FONT / baseSize;
  const atMin = natural.map((width) => width * minScale);
  const widths: number[] = [];
  let used = 0;
  for (const width of atMin) {
    if (widths.length && used + width > contentWidth) break;
    widths.push(width);
    used += width;
  }
  if (!widths.length) widths.push(contentWidth);
  return {
    widths,
    font: sans(SHARE_MIN_TABLE_FONT),
    keptColumns: widths.length,
    totalColumns: natural.length,
  };
}

function tableRows(
  block: Extract<ShareBlock, { type: "table" }>,
  context: BlockContext,
): FlowRow[] {
  const columnCount = Math.max(
    block.header.length,
    ...block.rows.map((row) => row.length),
    1,
  );
  const columns: string[][] = [];
  for (let index = 0; index < columnCount; index += 1) {
    columns.push([
      inlinesToPlainText(block.header[index] || []),
      ...block.rows.map((row) => inlinesToPlainText(row[index] || [])),
    ]);
  }
  const plan = planTableColumns(columns, context.width, context.measure);
  if (plan.keptColumns < plan.totalColumns) context.onTruncatedTable();
  const kept = plan.keptColumns;
  const headerFont: ShareFont = { ...plan.font, weight: 600 };
  const rowHeight = Math.round(plan.font.size * 2.4);
  const tableWidth = plan.widths.reduce((sum, width) => sum + width, 0);

  const drawRow = (
    cells: ShareInline[][],
    font: ShareFont,
    background?: string,
  ): FlowRow => ({
    height: rowHeight,
    render: (x, y) => {
      const items: ShareDrawItem[] = [];
      if (background) {
        items.push({
          kind: "rect",
          x,
          y,
          width: tableWidth,
          height: rowHeight,
          fill: background,
        });
      }
      let cursor = x;
      for (let index = 0; index < kept; index += 1) {
        const width = plan.widths[index];
        items.push({
          kind: "rect",
          x: cursor,
          y,
          width,
          height: rowHeight,
          stroke: SHARE_COLORS.tableBorder,
          lineWidth: 1,
        });
        const text = inlinesToPlainText(cells[index] || []);
        if (text) {
          items.push({
            kind: "text",
            x: cursor + TABLE_CELL_PADDING,
            y: y + Math.round((rowHeight - font.size * 1.2) / 2),
            text: clipToWidth(
              text,
              width - TABLE_CELL_PADDING * 2,
              font,
              context.measure,
            ),
            font,
            color: font.weight >= 600 ? SHARE_COLORS.text : SHARE_COLORS.muted,
          });
        }
        cursor += width;
      }
      return items;
    },
  });

  const rows: FlowRow[] = [spacer(8)];
  rows.push(drawRow(block.header, headerFont, SHARE_COLORS.tableHeader));
  for (const row of block.rows) rows.push(drawRow(row, plan.font));
  if (plan.keptColumns < plan.totalColumns) {
    const noteFont = sans(12, 400, true);
    rows.push({
      height: 24,
      render: (x, y) => [
        {
          kind: "text",
          x,
          y: y + 6,
          text: context.labels.tableTruncated,
          font: noteFont,
          color: SHARE_COLORS.faint,
        },
      ],
    });
  }
  rows.push(spacer(8));
  return rows;
}

function clipToWidth(
  text: string,
  maxWidth: number,
  font: ShareFont,
  measure: ShareMeasureContext,
): string {
  if (measure.measureText(text, font) <= maxWidth) return text;
  let current = "";
  for (const character of text) {
    if (measure.measureText(`${current}${character}…`, font) > maxWidth) break;
    current += character;
  }
  return `${current}…`;
}

function mathRows(
  block: Extract<ShareBlock, { type: "math" }>,
  context: BlockContext,
): FlowRow[] {
  const measured = context.measure.measureMath?.(block.tex, true, context.width);
  if (!measured) {
    context.onFallbackFormula();
    return paragraphRows(
      [{ type: "text", text: block.tex, code: true }],
      context,
      mono(14),
    );
  }
  const scale = Math.min(1, context.width / Math.max(1, measured.width));
  const width = measured.width * scale;
  const height = measured.height * scale;
  return [
    spacer(10),
    {
      height: Math.round(height),
      render: (x, y) => [
        {
          kind: "math",
          x: x + Math.round((context.width - width) / 2),
          y,
          width,
          height,
          tex: block.tex,
          display: true,
        },
      ],
    },
    spacer(10),
  ];
}

function imageRows(
  block: Extract<ShareBlock, { type: "image" }>,
  context: BlockContext,
  maxHeight: number,
): FlowRow[] {
  const natural = context.measure.imageSize?.(block.src);
  if (!natural || !(natural.width > 0) || !(natural.height > 0)) return [];
  const scale = Math.min(
    1,
    context.width / natural.width,
    maxHeight / natural.height,
  );
  const width = Math.round(natural.width * scale);
  const height = Math.round(natural.height * scale);
  return [
    spacer(8),
    {
      height,
      render: (x, y) => [
        {
          kind: "image",
          x,
          y,
          width,
          height,
          src: block.src,
          radius: 12,
        },
      ],
    },
    spacer(8),
  ];
}

function blockRows(
  block: ShareBlock,
  context: BlockContext,
  maxImageHeight: number,
): FlowRow[] {
  switch (block.type) {
    case "heading":
      return headingRows(block, context);
    case "paragraph":
      return paragraphRows(block.inlines, context);
    case "quote":
      return quoteRows(block, context);
    case "list":
      return listRows(block, context);
    case "code":
      return codeRows(block, context);
    case "table":
      return tableRows(block, context);
    case "math":
      return mathRows(block, context);
    case "image":
      return imageRows(block, context, maxImageHeight);
    case "rule":
      return [
        spacer(10),
        {
          height: 1,
          render: (x, y) => [
            {
              kind: "line",
              x,
              y,
              width: context.width,
              color: SHARE_COLORS.rule,
              thickness: 1,
            },
          ],
        },
        spacer(10),
      ];
    default:
      return [];
  }
}

// ---------------------------------------------------------------------------
// 页眉 / 页脚
// ---------------------------------------------------------------------------

function headerRows(
  labels: ShareCardLabels,
  context: BlockContext,
): { rows: FlowRow[]; height: number } {
  const rows: FlowRow[] = [];
  const titleLines = layoutInlines(
    [{ type: "text", text: labels.title || labels.brand, bold: true }],
    {
      baseFont: sans(24, 700),
      color: SHARE_COLORS.text,
      maxWidth: context.width,
      measure: context.measure,
      lineHeightRatio: 1.4,
    },
  ).slice(0, 3);
  rows.push(...linesToRows(titleLines));
  if (labels.subtitle) {
    rows.push(spacer(6));
    rows.push(
      ...linesToRows(
        layoutInlines([{ type: "text", text: labels.subtitle }], {
          baseFont: sans(13),
          color: SHARE_COLORS.faint,
          maxWidth: context.width,
          measure: context.measure,
        }),
      ),
    );
  }
  rows.push(spacer(14));
  rows.push({
    height: 1,
    render: (x, y) => [
      {
        kind: "line",
        x,
        y,
        width: context.width,
        color: SHARE_COLORS.rule,
        thickness: 1,
      },
    ],
  });
  rows.push(spacer(20));
  return { rows, height: rows.reduce((sum, row) => sum + row.height, 0) };
}

function footerItems(
  labels: ShareCardLabels,
  context: BlockContext,
  qrModules: readonly (readonly boolean[])[] | null,
  x: number,
  y: number,
  pageIndex: number,
  pageTotal: number,
): ShareDrawItem[] {
  const items: ShareDrawItem[] = [
    {
      kind: "line",
      x,
      y,
      width: context.width,
      color: SHARE_COLORS.rule,
      thickness: 1,
    },
  ];
  const top = y + 20;
  const hasQr = Boolean(qrModules && qrModules.length);
  const textWidth = context.width - (hasQr ? QR_SIZE + 20 : 0);
  items.push({
    kind: "text",
    x,
    y: top,
    text: labels.brand,
    font: sans(15, 700),
    color: SHARE_COLORS.text,
  });
  const taglineLines = layoutInlines(
    [{ type: "text", text: labels.tagline }],
    {
      baseFont: sans(12.5),
      color: SHARE_COLORS.muted,
      maxWidth: textWidth,
      measure: context.measure,
      lineHeightRatio: 1.5,
    },
  ).slice(0, 2);
  let cursor = top + 24;
  for (const line of taglineLines) {
    items.push(...shift(line.items, x, cursor));
    cursor += line.height;
  }
  if (labels.linkText) {
    items.push({
      kind: "text",
      x,
      y: cursor + 4,
      text: clipToWidth(labels.linkText, textWidth, sans(11.5), context.measure),
      font: sans(11.5),
      color: SHARE_COLORS.faint,
    });
  }
  if (hasQr && qrModules) {
    items.push({
      kind: "qr",
      x: x + context.width - QR_SIZE,
      y: top - 4,
      size: QR_SIZE,
      modules: qrModules,
    });
  }
  if (pageTotal > 1) {
    items.push({
      kind: "text",
      x: x + context.width,
      y: y + 4,
      text: labels.pageIndicator
        .replace("{index}", String(pageIndex))
        .replace("{total}", String(pageTotal)),
      font: sans(11.5, 600),
      color: SHARE_COLORS.faint,
      align: "right",
    });
  }
  return items;
}

const FOOTER_HEIGHT = 108;

// ---------------------------------------------------------------------------
// 主入口
// ---------------------------------------------------------------------------

export function layoutShareCard(
  messages: readonly ShareCardMessage[],
  labels: ShareCardLabels,
  measure: ShareMeasureContext,
  options: ShareLayoutOptions = {},
): ShareLayoutResult {
  const width = options.width ?? SHARE_CARD_WIDTH;
  const maxPageHeight = options.maxPageHeight ?? SHARE_MAX_PAGE_HEIGHT;
  const contentLeft = PAGE_MARGIN + CARD_PADDING;
  const contentWidth = width - contentLeft * 2;
  let truncatedTables = 0;
  let fallbackFormulas = 0;

  const context: BlockContext = {
    width: contentWidth,
    measure,
    labels,
    onTruncatedTable: () => {
      truncatedTables += 1;
    },
    onFallbackFormula: () => {
      fallbackFormulas += 1;
    },
  };

  const header = headerRows(labels, context);
  const chrome = PAGE_MARGIN * 2 + CARD_PADDING * 2 + FOOTER_HEIGHT;
  const firstPageBudget = maxPageHeight - chrome - header.height;
  const otherPageBudget = maxPageHeight - chrome;

  // --- 消息 → section --------------------------------------------------
  const sections: FlowSection[] = [];
  for (const message of messages) {
    const isUser = message.role === "user";
    const bubbleContentWidth = isUser
      ? Math.round(contentWidth * USER_BUBBLE_MAX_RATIO) - BUBBLE_PADDING_X * 2
      : contentWidth;
    const sectionContext: BlockContext = {
      ...context,
      width: Math.max(120, bubbleContentWidth),
    };
    const bodyRows: FlowRow[] = [];
    for (const block of message.blocks) {
      const rows = blockRows(
        block,
        sectionContext,
        otherPageBudget - BUBBLE_PADDING_Y * 2,
      );
      if (bodyRows.length && rows.length) bodyRows.push(spacer(BLOCK_GAP));
      bodyRows.push(...rows);
    }
    if (!bodyRows.length) continue;

    if (isUser) {
      // 气泡宽度取实际最宽的一行，右对齐——不是永远铺满 78%。
      const used = Math.max(
        ...bodyRows.map((row) =>
          Math.max(
            0,
            ...row
              .render(0, 0)
              .map((item) =>
                item.kind === "text"
                  ? item.x + measure.measureText(item.text, item.font)
                  : "width" in item
                    ? item.x + item.width
                    : 0,
              ),
          ),
        ),
        120,
      );
      const bubbleWidth = Math.min(
        Math.round(contentWidth * USER_BUBBLE_MAX_RATIO),
        Math.ceil(used) + BUBBLE_PADDING_X * 2,
      );
      sections.push({
        bubble: true,
        x: contentLeft + contentWidth - bubbleWidth,
        width: bubbleWidth,
        rows: [
          spacer(BUBBLE_PADDING_Y),
          ...bodyRows.map((row) => ({
            height: row.height,
            render: (x: number, y: number) =>
              row.render(x + BUBBLE_PADDING_X, y),
          })),
          spacer(BUBBLE_PADDING_Y),
        ],
      });
    } else {
      const speakerFont = sans(12, 600);
      const speakerRows: FlowRow[] = message.speaker
        ? [
            {
              height: 22,
              render: (x, y) => [
                {
                  kind: "text",
                  x,
                  y,
                  text: message.speaker,
                  font: speakerFont,
                  color: SHARE_COLORS.faint,
                },
              ],
            },
          ]
        : [];
      sections.push({
        bubble: false,
        x: contentLeft,
        width: contentWidth,
        rows: [...speakerRows, ...bodyRows],
      });
    }
    sections.push({
      bubble: false,
      x: contentLeft,
      width: contentWidth,
      rows: [spacer(SECTION_GAP)],
    });
  }

  // --- 分页 -------------------------------------------------------------
  interface PlacedRow {
    section: FlowSection;
    row: FlowRow;
  }
  const flat: PlacedRow[] = [];
  for (const section of sections) {
    for (const row of section.rows) flat.push({ section, row });
  }

  const pageBuckets: PlacedRow[][] = [];
  let bucket: PlacedRow[] = [];
  let used = 0;
  let budget = firstPageBudget;
  for (const placed of flat) {
    const height = Math.min(placed.row.height, budget);
    if (used > 0 && used + height > budget) {
      pageBuckets.push(bucket);
      bucket = [];
      used = 0;
      budget = otherPageBudget;
    }
    bucket.push(placed);
    used += height;
  }
  if (bucket.length || !pageBuckets.length) pageBuckets.push(bucket);

  const pageTotal = pageBuckets.length;
  const pages: SharePage[] = pageBuckets.map((rows, position) => {
    const pageIndex = position + 1;
    const contentTop =
      PAGE_MARGIN + CARD_PADDING + (pageIndex === 1 ? header.height : 0);
    const bodyHeight = rows.reduce((sum, placed) => sum + placed.row.height, 0);
    const pageHeight = Math.max(
      320,
      Math.round(contentTop + bodyHeight + FOOTER_HEIGHT + CARD_PADDING + PAGE_MARGIN),
    );
    const items: ShareDrawItem[] = [
      {
        kind: "rect",
        x: 0,
        y: 0,
        width,
        height: pageHeight,
        fill: SHARE_COLORS.pageBackground,
      },
      {
        kind: "rect",
        x: PAGE_MARGIN,
        y: PAGE_MARGIN,
        width: width - PAGE_MARGIN * 2,
        height: pageHeight - PAGE_MARGIN * 2,
        fill: SHARE_COLORS.card,
        stroke: SHARE_COLORS.cardBorder,
        lineWidth: 1,
        radius: 22,
      },
    ];
    if (pageIndex === 1) {
      let cursor = PAGE_MARGIN + CARD_PADDING;
      for (const row of header.rows) {
        items.push(...row.render(contentLeft, cursor));
        cursor += row.height;
      }
    }
    // 气泡底色：一个 section 可能被切到两页，底色按**本页落到的行范围**单独补一块。
    // 必须先于正文入队，否则会盖住字。
    let cursor = contentTop;
    let runSection: FlowSection | null = null;
    let runTop = cursor;
    const closeBubble = (bottom: number) => {
      if (!runSection?.bubble) return;
      items.push({
        kind: "rect",
        x: runSection.x,
        y: runTop,
        width: runSection.width,
        height: Math.max(1, bottom - runTop),
        fill: SHARE_COLORS.userBubble,
        radius: 18,
      });
    };
    for (const placed of rows) {
      if (placed.section !== runSection) {
        closeBubble(cursor);
        runSection = placed.section;
        runTop = cursor;
      }
      cursor += placed.row.height;
    }
    closeBubble(cursor);

    cursor = contentTop;
    for (const placed of rows) {
      items.push(...placed.row.render(placed.section.x, cursor));
      cursor += placed.row.height;
    }
    items.push(
      ...footerItems(
        labels,
        context,
        options.qrModules ?? null,
        contentLeft,
        pageHeight - PAGE_MARGIN - CARD_PADDING - FOOTER_HEIGHT,
        pageIndex,
        pageTotal,
      ),
    );
    return { index: pageIndex, width, height: pageHeight, items };
  });

  return { width, pages, truncatedTables, fallbackFormulas };
}
