import type { RefCallback } from "react";
import type { PersistedEditorVersion } from "../doc-editors/doc-io";

export interface Model3DWorkbenchState {
  viewerRef: RefCallback<HTMLElement>;
  title: string;
  sourceUrl: string;
  posterUrl: string;
  viewerReady: boolean;
  modelLoaded: boolean;
  loading: boolean;
  progress: number;
  error: string;
  notice: string;
  savedUrl: string;
  capturing: boolean;
  saving: boolean;
  downloading: boolean;
  dirty: boolean;
  editRevision: number;
  azimuth: number;
  elevation: number;
  zoom: number;
  autoRotate: boolean;
  exposure: number;
  shadowIntensity: number;
  shadowSoftness: number;
  background: string;
  animations: string[];
  animationName: string;
  animationPlaying: boolean;
  animationSpeed: number;
  setOrbit: (azimuth: number, elevation: number) => void;
  setZoom: (distancePercent: number) => void;
  resetCamera: () => void;
  setAutoRotate: (enabled: boolean) => void;
  setExposure: (value: number) => void;
  setShadowIntensity: (value: number) => void;
  setShadowSoftness: (value: number) => void;
  setBackground: (value: string) => void;
  selectAnimation: (name: string) => void;
  toggleAnimation: () => void;
  setAnimationSpeed: (value: number) => void;
  importModel: (file: File) => Promise<void>;
  openModelUrl: (url: string) => void;
  downloadScreenshot: () => Promise<void>;
  saveScreenshot: () => Promise<void>;
  downloadModel: () => Promise<void>;
  saveCopy: () => Promise<PersistedEditorVersion | null>;
  restoreRecovery: (payload: unknown) => boolean;
}
